#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-rubygems
Version  : 1.0.0
Release  : 7
URL      : https://rubygems.org/downloads/hoe-rubygems-1.0.0.gem
Source0  : https://rubygems.org/downloads/hoe-rubygems-1.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= Hoe Loves RubyGems
* http://github.com/jbarnette/hoe-rubygems
== Description
A Hoe plugin with additional RubyGems tasks. Provides support for
generating gemspec files and installing with a prefix.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-rubygems-1.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-rubygems.gemspec

%build
gem build rubygem-hoe-rubygems.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-rubygems-1.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-rubygems-1.0.0
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/hoe-rubygems-1.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/Hoe/RubyGems/cdesc-RubyGems.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/Hoe/RubyGems/define_rubygems_tasks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/Hoe/cdesc-Hoe.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/page-CHANGELOG_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/hoe-rubygems-1.0.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/.autotest
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/CHANGELOG.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/hoe-rubygems-1.0.0/lib/hoe/rubygems.rb
/usr/lib64/ruby/gems/2.2.0/specifications/hoe-rubygems-1.0.0.gemspec
